### ISSUE TITLE
Licence 

### ISSUE THREAD

**Issue by zaverichintan** [GravityProject/gravity#109]
We can add licence tag to all our files, 
I am not sure how to go through the process of licencing. 
But it's needed as an open source project

**Comment by pmuens** [comment]
What if we put the MIT License in the root of the project?

**Comment by zaverichintan** [comment]
I think we should add it in all files on header section as other projects are also having it.

**Comment by zaverichintan** [comment]
Info on MIT license - 
https://opensource.org/licenses/MIT
To add it to github -  
https://help.github.com/articles/open-source-licensing/

**Comment by pmuens** [comment]
Thank you. I think for the first version an addition of the MIT license is sufficient (as Meteor does it). We can add the headers later on if we need to.

**Comment by zaverichintan** [comment]
Oh thats perfectly fine. Can someone use this source code and use it for commercial propose will it be ok?

**Comment by pmuens** [comment]
Yes. I think we should use the MIT license which permits this!

**Comment by zaverichintan** [comment]
PR successfully submitted
https://github.com/GravityProject/gravity/pull/110
