### ISSUE TITLE
Slack chat 

### ISSUE THREAD

**Issue by zaverichintan** [GravityProject/gravity#112]
I have made an account on slack to discuss about the development. 
Here's the link 
http://joingravity.slack.com/
Kindly join it

**Comment by pmuens** [comment]
Great idea! Thank you very much for all your effort!

**Comment by pmuens** [comment]
Do you have a sign up page? Your link points to the sign in page.

**Comment by zaverichintan** [comment]
You have to sign in to get access

**Comment by zaverichintan** [comment]
Everyone! Kindly drop your mail ID here

**Comment by happyoniens** [comment]
@zaverichintan can you enable email signup as described [here](https://get.slack.help/hc/en-us/articles/201330256-Inviting-new-members-to-your-Slack-team) so every member can create an account on their own?

**Comment by pmuens** [comment]
That's a good idea. This way we won't need to post our E-Mail address here!

**Comment by zaverichintan** [comment]
There's a security check where domains are to be specified. I am enabling Gmail, yahoo, rediff. For time being

**Comment by happyoniens** [comment]
Maybe we should use something like [this](https://github.com/outsideris/slack-invite-automation)

**Comment by pmuens** [comment]
Yep. That can be easily deployed to Heroku.

**Comment by happyoniens** [comment]
@pmuens can you upload this, so we can make the signup page something like slack.joingravity.com?
I have never worked with Heroku so I don't know if this is possible.

**Comment by zaverichintan** [comment]
Forward me your ID at Zaverichintan5@gmail.com so that I can send you the Auth keys

**Comment by pmuens** [comment]
Alright guys. I'll look into this!

**Comment by pmuens** [comment]
https://joingravity-slack.herokuapp.com

**Comment by zaverichintan** [comment]
Great 👍
