### ISSUE TITLE
Submit post by shift + enter

### ISSUE THREAD

**Issue by cycorld** [GravityProject/gravity#118]
How about implementing 'shift + enter' as a short key for submit post?

**Comment by zaverichintan** [comment]
Yea can be done. Is it really that essential?  What others feel like?

**Comment by pmuens** [comment]
Great. There's a library called mousetrap which is kinda nice: https://craig.is/killing/mice

Here you can see how it would be used (although it's CoffeeScript code): https://github.com/Goltfisch/james/blob/master/client/views/workspaces/workspace.coffee#L189-L200

**Comment by mattvella07** [comment]
Yea I think this would be pretty cool too.  I can work on this, unless someone else has already started.

**Comment by pmuens** [comment]
Great! I think no one else is on it!

**Comment by mattvella07** [comment]
Done!

**Comment by cycorld** [comment]
Great!
