### ISSUE TITLE
Follow users

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#12]
Follow users so that posts will pop up in the timeline (#23).

**Comment by cirsca** [comment]
We implemented something like this on a recent learning project. What we did was add a property to the user's profile that was an array called "subscriptions" that held the _id of whatever the user was subscribing to. 

I think it was using the user creation hook to create an array on user create. And then in their feed it was Collection.find({_id: $in profile.subscription}) or something along those lines. 

I could copy/pasta what we did and you can modify it if you think it'll help.

**Comment by pmuens** [comment]
Hey @cirsca thank you for mentioning that. It would be great if you could share the code! :+1:

**Comment by cirsca** [comment]
Meteor.users.before.insert(function (userId, doc) {
      doc.profile.subscriptions = [];
    });

would be the creation hook to create an empty array under the user's profile property and to toggle the subscriptions we had:

    subscribeToggle: function (curUser, thisId) {
       var position = curUser.profile.subscriptions.indexOf(thisId);

        if (position >=0) {
          Meteor.users.update({_id: this.userId}, {$pull: {'profile.subscriptions': thisId}});
        } else {
          Meteor.users.update({_id: this.userId}, {$push: {'profile.subscriptions': thisId}});

        }

        return; 
     }

with curUser being the current user object and thisId being the id of whatever we are subscribing to, both of which are passed to us by our method call which we had look something like this:

     var curUser = Meteor.user();
      var thisId = this._id;
      Meteor.call('subscribeToggle', curUser, thisId);

I'm not sure where our `Collection.find()` code is. I'll see if I can find it. Let me know if this helps your idea!

**Comment by pmuens** [comment]
@cirsca thanks!
