### ISSUE TITLE
Gravity Website is Not Up

### ISSUE THREAD

**Issue by ubuntume** [GravityProject/gravity#130]
Hello. I've been really working with Google to hone in on the not so mainstream query results and your project came up. 

I went to visit your website and it didn't come up and had an error. I am very interested in growing in my coding knowledge. I am also looking for a few people I can help out along the way. 

Sidenote - I sell web hosting so if you ever need any dedicated machines I'm actually hoping to become an ISP. Anywho, I definitely would like to find a open source social networking script that I can run on my own dedicated machine. 

So yea which ever one I wind up picking will be that one. Cheers.

**Comment by zaverichintan** [comment]
http://joingravity.herokuapp.com is the link to the Gravity website.
