### ISSUE TITLE
Use React?

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#24]
Do you think it's great to move to React? I've done a few projects with React so far but I'm not sure whether this is a good idea for this project. Maybe it's a little bit too overkill and Blaze is sufficient?

**Comment by niallobrien** [comment]
I think until we see more GraphQL implementations in the wild, it might be best to stick with Blaze as React still has the same data dependencies as Blaze.

**Comment by pmuens** [comment]
Yes, I think so too.
The encapsulation of functionality into components is great, but overall IMHO I'm faster writing blaze code rather than React components.

**Comment by ai10** [comment]
https://github.com/ipy/meteor-webpack-react-typescript.git

npm install react-toolkit
add kadira:flow-router
add kadira:react-layout

**Comment by michaltakac** [comment]
You can migrate to React bit-by-bit when you decide in the future.

**Comment by nchenbang** [comment]
If you have decided to stick with Blaze for this project, I think you can have a look at the blaze component which allows you to write reusable components in Blaze.

**Comment by niallobrien** [comment]
@nchenbang The API for Blaze Components isn't the best either though...

**Comment by nchenbang** [comment]
Well, I don't think you've much choice if you want to write components in Blaze.

**Comment by pmuens** [comment]
Yes, maybe we should transition to Reactive. But I'm not sure if it's a safe bet.

Do you guys have any information how the MDG will deal with Blaze in the future? There are some rumors that the built React on top of it, but I'm not sure if it's true...

**Comment by niallobrien** [comment]
Sashko answered my Blaze question during the recent Crater AMA with MDG. Basically it doesn't make sense for MDG to support Blaze any longer, according to them that is.

**Comment by pmuens** [comment]
@niallobrien thanks! Good to know!

**Comment by niallobrien** [comment]
Let me clarify, they will accept PRs etc. and Blaze is unlikely to go anywhere right now, but I don't think Blaze 2.0 is on their roadmap. Also, the sheer number of time saving packages that are available for Blaze is a no-brainer imo.

**Comment by pmuens** [comment]
Yes, that's correct.
Having used React in some prior projects (Meteor and not Meteor related) I don't see any benefit if one does not use dump components and stuff like that.

**Comment by niallobrien** [comment]
Perhaps further down the road when there's some more Meteor specific React packages available, it might be worth revisiting, but for now I think this issue should be closed.

**Comment by nchenbang** [comment]
Following the official announcement on the future of Blaze, should we revise our previous decision and consider to use React in this project?

**Comment by niallobrien** [comment]
Personally, I'd continue as planned and wait for Blaze 2. No need to jump into the React boat just yet imo.

**Comment by pmuens** [comment]
Yes, good question.

This is the discussion BTW:
https://forums.meteor.com/t/next-steps-on-blaze-and-the-view-layer/13561

I would also wait a little bit and watch what happens. Many apps depend on Blaze these days and we should have enough time for the transition when things are a little bit cleaner (IMHO).

**Comment by pmuens** [comment]
After reading this (https://www.discovermeteor.com/blog/blaze-react-meteor/) blog post by the guys of discover meteor I think it's a good thing to use React for new Meteor projects as recommended.

I'll start the transition to React the upcoming weeks.

**Comment by Lenin7** [comment]
Any way to contribute to the React branch?

**Comment by pmuens** [comment]
@Lenin7 thanks for reaching out. React is not yet implemented so feel free to open a PR!
