### ISSUE TITLE
Allow username for sign in

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#29]

**Comment by nchenbang** [comment]
I saw that you are using
    
    Meteor.loginWithPassword(user.email, user.password, (error, result) => {
      if (error) {
        Bert.alert(error.reason, 'danger', 'growl-top-right');
      } else {
        FlowRouter.go('/');
      }
    });

to sign in user which by default can receive either username or email as the first argument so I think you just need to modify the input type and label name for the sign_in.html for this to work

**Comment by pmuens** [comment]
Yes, thank you. That's correct. I'll update the login method so that both can be used!

**Comment by michaltakac** [comment]
What do you think about using useraccounts:foundation and useraccounts:flow-router? You can easily customize it and extend it with custom fields.

https://atmospherejs.com/useraccounts/flow-routing

**Comment by pmuens** [comment]
Good point. I looked at it in the past but I couldn't manage to get it working with different routes (One view should display only the sign up form, the other one the sign in form, ...).

**Comment by pmuens** [comment]
Closed with c83247f
