### ISSUE TITLE
Power-off icon to sign out is ambiguous

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#30]

**Comment by micahalcorn** [comment]
+1

**Comment by michaltakac** [comment]
Swap it for dropdown menu, where link to user profile and logout can be added?

**Comment by pmuens** [comment]
Good idea @michaltakac 
User profiles will be one of the upcoming features so there should be a convenient way for the user to get to his settings / update profile menu.

Only "harder" part would be the mobile friendliness.
