### ISSUE TITLE
Add visible reference to GitHub repository

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#44]
Add a reference to the GitHub repository so that all users can see it directly (maybe with the help of a bottom fixed div) in an unobtrusive way. But don't use the "Fork me on GitHub" banner.

**Comment by michaltakac** [comment]
+1, maybe add footer text (copyright, made with <3 by etc. :D) to this fixed div on the bottom of layout and add link to github repo there. Fixed bottom div is great idea because it wont be burried down there under all posts :+1:
