### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#5]
Maybe solved with #4 ? Do we need a chat?

**Comment by Letladi** [comment]
Yes we do need it..

**Comment by pmuens** [comment]
Should this be a kind of big group chat or a chat with channels (like Slack) and direct messages?

**Comment by Letladi** [comment]
Channels/Groups seem like a good idea, but direct messages can be included as well.

**Comment by pmuens** [comment]
:+1:

**Comment by michaltakac** [comment]
+1 @Letladi
