### ISSUE TITLE
Add web profiles

### ISSUE THREAD

**Issue by mbaur** [GravityProject/gravity#55]
Possibility to link e.g. Twitter, GitHub, Facebook profiles in gravity account.

**Comment by cirsca** [comment]
Would we want the user to be able to sign-in with any of them and still be led to the same gravity account or have it to where the user can sign-in with a social media account but also add links to other social media profiles without having the ability to use those links to sign-in?

I have some code for the latter of the two but haven't found a good secure way of doing it for the former.

**Comment by 8mylez** [comment]
@cirsca i think @mbaur thought about the possibility to show other people your web profiles (e.g. twitter, github, Facebook ...).

@pmuens had the idea to make a text input, where the user can copy all his web profile links separated with commas. On the profile view this links would be visible.

The sign up via oauth should be a new issue.

**Comment by pmuens** [comment]
Yes, @8mylez is correct. It's discussed in #35

**Comment by cirsca** [comment]
Is anyone else working on this? If not, I'll try to get a PR for it tonight or tomorrow.

**Comment by 8mylez** [comment]
@cirsca if you like, you can make a PR. :)

**Comment by pmuens** [comment]
@cirsca great! It would be cool if the user can enter an arbitrary amount of links in a textarea separated by commas or newlines. This long text should be splitter up into the corresponding links when it's rendered on the users profile view.

**Comment by mattvella07** [comment]
@pmuens Has this been implemented already?

**Comment by pmuens** [comment]
@mattvella07 not yet.
