### ISSUE TITLE
1:1 messages

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#6]
Write other users a private message.

**Comment by pmuens** [comment]
May relate to #5

**Comment by mattvella07** [comment]
I think this could be something in addition to #5.  I think of this more like email (where you can send to someone even when they aren't online) and #5 more like chat (where the other person has to be online).  Just my thoughts.  I would like to work on this one though :raised_hands:

**Comment by pmuens** [comment]
@mattvella07 great. Yes, it should support offline usage. Maybe something like the Facebook messenger. I'll assign you!

**Comment by mattvella07** [comment]
@pmuens Sounds good, I'm working on it

**Comment by pmuens** [comment]
Great! Thanks!
