### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#66]
Add a linter which is run automatically during development. So that the code is checked automatically if the code conventions are met.

**Comment by nchenbang** [comment]
Do you want to use the same configuration that Meteor uses or you've your own preferred configuration in your mind?

**Comment by pmuens** [comment]
I think the same as Meteor should be sufficient!

**Comment by nchenbang** [comment]
Do you mean this one [JSHint](https://github.com/raix/Meteor-jshint)? I'm not sure if that package is still maintained but according to this [meteor todos](https://github.com/meteor/todos), you just need to add these three files

- .eslintignore
- .eslintrc
- .eslintrc-meteor 

and then run `eslint.` to check whether your code matches the MDG style guide. If you want the linter to run automatically during development maybe you can consider to setup a linter in your IDE or text editor and reuse the same config. (I'm using sublime text which is really easy to do this)

I just tried to run the `eslint.` and the result is this
`✖ 172 problems (155 errors, 17 warnings)`

**Comment by pmuens** [comment]
Thank you.

https://github.com/meteor/meteor/tree/devel/packages/jshint this package looks nice and it's maintained by the MDG.

Maybe we can utilize it!

**Comment by nchenbang** [comment]
Do you know if there is any way to convert eslint rules into jshint?  The problem I'm facing right now is MDG only provides eslint configuration for their official style guide and you can have a look [here] (https://github.com/meteor/meteor/blob/devel/scripts/admin/eslint/.eslintrc).

**Comment by pmuens** [comment]
Hmm. No, I have absolutely no clue...

**Comment by nchenbang** [comment]
Ok, I've found the solution, just stumbled across this awesome [package] (https://github.com/dburles/meteor-eslint) for adding eslint plugin instead of jshint plugin into the Meteor build system. 

Would you mind me sending in the PR?

**Comment by pmuens** [comment]
Great! Yeah, please send the PR! :+1:
