### ISSUE TITLE
Code in a post

### ISSUE THREAD

**Issue by thwillingham** [GravityProject/gravity#82]
When adding some HTML/JavaScript to a post, the text disappears after clicking submit.  
Case in point:  I tried to enter <script type="text/javascript">alert("hello, world!")</script> as my first post, and nothing actually posted.

**Comment by pmuens** [comment]
Good catch :+1: . I think this has something to do with sanitizing the input.

**Comment by zaverichintan** [comment]
@pmuens found something?

**Comment by pmuens** [comment]
The sanitizing of Meteor will prevent this. I think that #8 and #43 are related to this and an implementation of those two issues will resolve the issue.

**Comment by zaverichintan** [comment]
Done.
