### ISSUE TITLE
Confirmation Popups

### ISSUE THREAD

**Issue by mattvella07** [GravityProject/gravity#85]
I noticed that we are using the default javascript confirm for delete confirmation.  What do you all think about using something like SweetAlert: https://atmospherejs.com/kevohagan/sweetalert?

**Comment by pmuens** [comment]
Yes. Good idea.

SweetAlerts are great. But it should get some custom styles (Skeleton breaks the SweetAlert styles) so that it looks nice.

**Comment by mattvella07** [comment]
I have been experimenting with Sweet Alerts, what do you think of these?  For deleting a post and a message.

![screen shot 2016-03-08 at 1 52 50 am](https://cloud.githubusercontent.com/assets/9948628/13594222/924ccd20-e4d0-11e5-8175-4750f54b1df8.png)

![screen shot 2016-03-08 at 1 53 04 am](https://cloud.githubusercontent.com/assets/9948628/13594223/9251334c-e4d0-11e5-810b-11d0bbdc3c6c.png)

**Comment by mattvella07** [comment]
Looks like the border got cut off in my screenshot, but it is there.

**Comment by pmuens** [comment]
Thank you! That looks great. Just submit a PR so I can merge it.
