### ISSUE TITLE
Stay in 1:1 message after message is submitted

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#89]
It would be great if one could stay in the 1:1 message after the message was sent.

@mattvella07 Could you take a look at it? Thanks!

**Comment by mattvella07** [comment]
@pmuens Yea definitely.  Just to clarify, you want to stay in the "compose" section after the sent message right?

**Comment by pmuens** [comment]
Yes, when I have a chat open and submit a message. It would be great when I stay in the open chat.

**Comment by mattvella07** [comment]
That's a good idea, I can work on that later today.

**Comment by pmuens** [comment]
Awesome. Thank you!

**Comment by mattvella07** [comment]
Created pull request for this, I think this is what you were referencing but check it out and let me know what you think.  When creating a new message it goes back to the "all messages" section but when replying to one it stays in that area.

**Comment by mattvella07** [comment]
Completed :+1:
