### ISSUE TITLE
Dropdown with available usernames when composing message

### ISSUE THREAD

**Issue by pmuens** [GravityProject/gravity#90]
Get a list with autocompletion for available usernames when a message is composed.

**Comment by mattvella07** [comment]
I was thinking about this too, I can look into it.  Do you think it should have all users or just users you are following?

**Comment by pmuens** [comment]
Hmm. The coolest would be to write anyone. Otherwise you need to follow the user beforehand which might seem a little bit tedious.

We could think of another version later on.

**Comment by mattvella07** [comment]
Yea I agree.  I can look into this.

**Comment by pmuens** [comment]
Thanks :+1: You're a really valuable member of this organization!

**Comment by mattvella07** [comment]
Thanks!  This is a really cool project, I like working on it.

**Comment by happyoniens** [comment]
I think this issue can be closed, since #92 is merged.

**Comment by mattvella07** [comment]
:+1:

**Comment by pmuens** [comment]
@happyoniens Yep. You're right. Forgot that. Thanks!
