### ISSUE TITLE
Text Overflowing DIV on Post

### ISSUE THREAD

**Issue by mattvella07** [GravityProject/gravity#93]
I noticing when I posted a post with a long URL it overflowed the bounds of the DIV, see screenshot below:

<img width="1440" alt="screen shot 2016-03-11 at 9 20 11 am" src="https://cloud.githubusercontent.com/assets/9948628/13704636/ddf6911a-e76a-11e5-9196-8ab6f6f18d6e.png">

**Comment by pmuens** [comment]
Thanks for reporting. How should we fix that? Just an `overflow: hidden` or a scroll?

**Comment by mattvella07** [comment]
I think if we add this to the less file for Feed page it should work: 

.post {
  overflow-wrap: break-word;
  word-wrap: break-word;
}

I'm not at my personal computer (which has the repo) so I just tried in the browser and looks like it works.

**Comment by pmuens** [comment]
Great. Thanks for checking that out!
